#!/bin/sh
set -x

# This file is on root of the training project
DIR="$(dirname $0)"

# Find all directories to remove to have a clean training from scratch

# Installed modules
find $DIR -name node_modules -type d -exec rm -rf {} /dev/null \;

# Version locking file
find $DIR -name package-lock.json -exec rm -rf {} /dev/null \;

# Some autogenerated projects 
rm -rf $DIR/packages/training-10-modules-natives-level2/cluster/1-no-container
rm -rf $DIR/packages/training-21-complete-app/koa/koa-swagger-decorator
rm -rf $DIR/packages/training-21-complete-app/expressjs/mywebapp
rm -rf $DIR/packages/training-21-complete-app/loopback4/myapp
rm -rf $DIR/packages/training-21-complete-app/nestjs/myproject

# Globally installed modules
[ -d $DIR/packages/training-21-complete-app/nestjs ] && (cd $DIR/packages/training-21-complete-app/nestjs; npm uninstall -g nest)

